global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'butler-core'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names: ['autonomous-butler']
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true